---
- name: Wait for hana system replication to complete
  shell: "{{ hana_db_env }} && {{ hana_replication_status_command }}"
  become: true
  become_user: "{{ hana_sid | lower }}adm"
  register: hsrstatus
  until: hana_replication_status_ok in hsrstatus.stdout
  retries: "{{ task_retries }}"
  delay: "{{ task_delay }}"
  ignore_errors: true
  failed_when: "hsrstatus.rc not in [ 0, 10, 11, 12, 13, 14, 15 ]"
...
