
#############################################################
# Export Terraform variable values to an Ansible var_file.
#############################################################

#### HA Infra variables.

resource "local_file" "ha_ansible_infra-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

# INFRA variables
api_key: "${var.ibmcloud_api_key}"
region: "${var.REGION}"
ha_password: "${var.ha_password}"

hdb_iphost1: "${data.ibm_is_instance.db-vsi-1.primary_network_interface[0].primary_ip[0].address}"
hdb_iphost2: "${data.ibm_is_instance.db-vsi-2.primary_network_interface[0].primary_ip[0].address}"
hdb_hostname1: "${data.ibm_is_instance.db-vsi-1.name}"
hdb_hostname2: "${data.ibm_is_instance.db-vsi-2.name}"

app_iphost1: "${data.ibm_is_instance.app-vsi-1.primary_network_interface[0].primary_ip[0].address}"
app_iphost2: "${data.ibm_is_instance.app-vsi-2.primary_network_interface[0].primary_ip[0].address}"
app_hostname1: "${data.ibm_is_instance.app-vsi-1.name}"
app_hostname2: "${data.ibm_is_instance.app-vsi-2.name}"

app_instanceid1: "${data.ibm_is_instance.app-vsi-1.id}"
app_instanceid2: "${data.ibm_is_instance.app-vsi-2.id}"
hdb_instanceid1: "${data.ibm_is_instance.db-vsi-1.id}"
hdb_instanceid2: "${data.ibm_is_instance.db-vsi-2.id}"

alb_ascs_hostname: "${data.ibm_is_lb.alb-ascs.hostname}"
alb_ers_hostname: "${data.ibm_is_lb.alb-ers.hostname}"
alb_hana_hostname: "${data.ibm_is_lb.alb-hana.hostname}"
...
    DOC
  filename = "ansible/hainfra-vars.yml"
}

#### SAP-APP variables.

resource "local_file" "app_ansible_saps4app-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_ascs_instance_number: "${var.sap_ascs_instance_number}"
sap_ers_instance_number: "${var.sap_ers_instance_number}"
sap_ci_instance_number: "${var.sap_ci_instance_number}"
sap_aas_instance_number: "${var.sap_aas_instance_number}"
sap_main_password: "${var.sap_main_password}"

hdb_concurrent_jobs: "${var.hdb_concurrent_jobs}"

#SAP S/4HANA APP Installation kit path
kit_sapcar_file: "${var.kit_sapcar_file}"
kit_swpm_file: "${var.kit_swpm_file}"
kit_sapexe_file: "${var.kit_sapexe_file}"
kit_sapexedb_file: "${var.kit_sapexedb_file}"
kit_igsexe_file: "${var.kit_igsexe_file}"
kit_igshelper_file: "${var.kit_igshelper_file}"
kit_saphotagent_file: "${var.kit_saphotagent_file}"
kit_hdbclient_file: "${var.kit_hdbclient_file}"
kit_s4hana_export: "${var.kit_s4hana_export}"
...
    DOC
  filename = "ansible/saps4app-vars.yml"
}

#### HANADB variables.

resource "local_file" "db_ansible_saphana-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#HANA DB configuration
hana_sid: "${var.hana_sid}"
hana_profile: "${var.DB-PROFILE}"
hana_sysno: "${var.hana_sysno}"
hana_main_password: "${var.hana_main_password}"
hana_system_usage: "${var.hana_system_usage}"
hana_components: "${var.hana_components}"

#SAP HANA Installation kit path
kit_saphana_file: "${var.kit_saphana_file}"
...
    DOC
  filename = "ansible/saphana-vars.yml"
}

#### Integrate all variables for sap file shares in one.

resource "null_resource" "file_shares_ansible_vars" {
  depends_on = [module.file-shares]

  provisioner "local-exec" {
    working_dir = "ansible"
    command = <<EOF
    echo -e "---\n`cat fileshare_*`\n...\n" > fileshares-vars.yml; rm -rf fileshare_*; echo done
      EOF
      }
}
