
#############################################################
# Export Terraform variable values to an Ansible var_file.
#############################################################

#### HA Infra variables.

resource "local_file" "ha_ansible_infra-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

# INFRA variables
hdb_host1: "${module.db-vsi.HANA-DB-PRIVATE-IP-VSI1}"
hdb_host2: "${module.db-vsi.HANA-DB-PRIVATE-IP-VSI2}"

app_host1: "${module.app-vsi.SAP-APP-PRIVATE-IP-VSI1}"
app_host2: "${module.app-vsi.SAP-APP-PRIVATE-IP-VSI2}"
...
    DOC
  filename = "ansible/hainfra-vars.yml"
}

#### SAP-APP variables.

resource "local_file" "app_ansible_saps4app-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#SAP system configuration
sap_sid: "${var.sap_sid}"
sap_ascs_instance_number: "${var.sap_ascs_instance_number}"
sap_ci_instance_number: "${var.sap_ci_instance_number}"
sap_main_password: "${var.sap_main_password}"

#HANA config
hdb_sid: "${var.hana_sid}"
app_profile: "${var.APP-PROFILE}"
hdb_instance_number: "${var.hana_sysno}"
hdb_main_password: "${var.hana_main_password}"
# Number of concurrent jobs used to load and/or extract archives to HANA Host
hdb_concurrent_jobs: "${var.hdb_concurrent_jobs}"

#SAP S/4HANA APP Installation kit path
kit_sapcar_file: "${var.kit_sapcar_file}"
kit_swpm_file: "${var.kit_swpm_file}"
kit_sapexe_file: "${var.kit_sapexe_file}"
kit_sapexedb_file: "${var.kit_sapexedb_file}"
kit_igsexe_file: "${var.kit_igsexe_file}"
kit_igshelper_file: "${var.kit_igshelper_file}"
kit_saphotagent_file: "${var.kit_saphotagent_file}"
kit_hdbclient_file: "${var.kit_hdbclient_file}"
kit_s4hana_export: "${var.kit_s4hana_export}"
...
    DOC
  filename = "ansible/saps4app-vars.yml"
}


#### HANADB variables.

resource "local_file" "db_ansible_saphana-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

#HANA DB configuration
hana_sid: "${var.hana_sid}"
hana_profile: "${var.DB-PROFILE}"
hana_sysno: "${var.hana_sysno}"
hana_main_password: "${var.hana_main_password}"
hana_system_usage: "${var.hana_system_usage}"
hana_components: "${var.hana_components}"

#SAP HANA Installation kit path
kit_saphana_file: "${var.kit_saphana_file}"
...
    DOC
  filename = "ansible/saphana-vars.yml"
}


#### Integrate all variables for sap file shares in one.

resource "null_resource" "file_shares_ansible_vars" {
  depends_on = [module.file-shares]

  provisioner "local-exec" {
    working_dir = "ansible"
    command = <<EOF
    echo -ne "---\n`cat fileshare_usrsap-*`\n...\n" > fileshares-vars.yml; rm -rf fileshare_usrsap-*; echo done
      EOF
      }
}
