---
- name: Generate parameter file for sapinst
  template:
      src: pasconfig.cfg
      dest: "{{ sap_kit }}/pasconfig.params"

- name: Start SAP NW PAS installation
  shell: "{{ sap_kit }}/swpm/sapinst SAPINST_INPUT_PARAMETERS_URL={{ sap_kit }}/pasconfig.params SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"

- name: Cleanup
  file:
    path: "{{ sap_kit }}"
    state: absent
...
