---
- name: Get PKI from primary node
  fetch:
    src: "{{ pki_key }}"
    dest: /tmp/
    flat: yes
  loop:
    - /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT
    - /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY
  loop_control:
    loop_var: pki_key

- name: Configure HANA parameter replication
  blockinfile:
    path: /hana/shared/{{ hana_sid | upper }}/global/hdb/custom/config/global.ini
    backup: yes
    block: |
      
      [inifile_checker]
      replicate = true

- name: Enable HSR on primary node
  shell: |
      source /usr/sap/{{ hana_sid | upper }}/home/.sapenv.sh && \
      /usr/sap/{{ hana_sid | upper }}/HDB{{ hana_sysno }}/exe/hdbnsutil \
      -sr_enable --name=SITE_A
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ hana_sid | lower }}adm"
  register: hsrconfig
  changed_when: "'successfully enabled system as system replication' in hsrconfig.stdout"
...
