---
- name: Create HANA hooks directory
  file:
    path: "/hana/shared/{{ hana_hooks_dir }}"
    state: directory
    owner: "{{ hana_sid | lower }}adm"
    group: sapsys
    mode: 0755

- name: Copy HANA hooks
  copy:
    src: /usr/share/SAPHanaSR/srHook/SAPHanaSR.py
    dest: "/hana/shared/{{ hana_hooks_dir }}"
    remote_src: yes
    owner: "{{ hana_sid | lower }}adm"
    group: sapsys
    mode: 0755

- name: Stop HANADB instance
  shell: |
      /usr/sap/{{ hana_sid | upper }}/HDB{{ hana_sysno }}/HDB stop
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ hana_sid | lower }}adm"
  register: hanadbstop
  changed_when: "'StopSystem' in hanadbstop.stdout"

- name: Configure HANA hooks
  blockinfile:
    path: /hana/shared/{{ hana_sid | upper }}/global/hdb/custom/config/global.ini
    backup: yes
    block: |
      
      [ha_dr_provider_SAPHanaSR]
      provider = SAPHanaSR
      path = /hana/shared/{{ hana_hooks_dir }}
      execution_order = 1

      [trace]
      ha_dr_saphanasr = info

- name: Generate sudoers file HANA Hook replication
  template:
      src: 20-saphana.j2
      dest: /etc/sudoers.d/20-saphana
...
