---
- name: Create /usr/sap/kit directory
  file:
    path: "{{ sap_kit }}"
    state: directory
    mode: 0777

- name: Create "{{ sap_kit }}"/swpm directory
  file:
    path: "{{ sap_kit }}/swpm"
    state: directory
    mode: 0777

- name: Copy "{{ kit_sapcar_file }}" kit to target
  copy:
    src: "{{ kit_sapcar_file }}"
    dest: "{{ sap_kit }}/sapcar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_swpm_file }}" kit to target
  copy:
    src: "{{ kit_swpm_file }}"
    dest: "{{ sap_kit }}/swpm.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_saphotagent_file }}" kit to target
  copy:
    src: "{{ kit_saphotagent_file }}"
    dest: "{{ sap_kit }}/saphotagent.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexe_file }}" kit to target
  copy:
    src: "{{ kit_sapexe_file }}"
    dest: "{{ sap_kit }}/sapexe.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexedb_file }}" kit to target
  copy:
    src: "{{ kit_sapexedb_file }}"
    dest: "{{ sap_kit }}/sapexedb.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_igsexe_file }}" kit to target
  copy:
    src: "{{ kit_igsexe_file }}"
    dest: "{{ sap_kit }}/igsexe.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_igshelper_file }}" kit to target
  copy:
    src: "{{ kit_igshelper_file }}"
    dest: "{{ sap_kit }}/igshelper.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_hdbclient_file }}" kit to target
  copy:
    src: "{{ kit_hdbclient_file }}"
    dest: "{{ sap_kit }}/hdbclient.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_s4hana_export }}" kit to target
  copy:
    src: "{{ kit_s4hana_export }}/"
    dest: "{{ sap_kit }}"
    owner: root
    group: root
    mode: 0777

- name: Extract SWPM archive
  command: "{{ sap_kit }}/sapcar -xf {{ sap_kit }}/swpm.sar -R {{ sap_kit }}/swpm"
...
